name: build and test
on:
  push:
    branches:
      - "main"
  pull_request:

env:
  SLN: "./src/XlsxCompare.sln"

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Install dependencies
        run: dotnet restore "${SLN}"
      - name: Build
        run: dotnet build --configuration Release --no-restore "${SLN}"
      - name: test
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: ${{ env.SLN }}
          no_restore: true
          set_check_status_from_test_outcome: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
