name: Release

# https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863
on:
  pull_request:
  push:
    tags:
      - "v*"

env:
  APP: "./src/XlsxCompare"

jobs:
  # verify_commit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Verify commit exists in origin/main
  #       run: |
  #         git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
  #         git branch --remote --contains | grep origin/main

  binaries:
    #    needs: verify_commit
    runs-on: ubuntu-latest
    name: create standalone binaries
    strategy:
      matrix:
        rid:
          - win-x64
          - linux-x64
          - osx-x64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Create the self-contained binary
        run: dotnet publish --configuration Release "${APP}" -r ${{ matrix.rid }} -o out/${{ matrix.rid }} --self-contained true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.rid }} binary
          path: out/${{ matrix.rid }}/*

  release:
    needs: binaries
    runs-on: ubuntu-latest
    steps:
      - name: download all binaries
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      # - uses: "marvinpinto/action-automatic-releases@v1"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     prerelease: false
      #     files: |
      #       LICENSE.txt
      #       *.jar
